apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${CA_CRT}
    server: https://${CLUSTER_HOST_PORT}
  name: kind-${KIND_CLUSTER_NAME}
contexts:
- context:
    cluster: kind-${KIND_CLUSTER_NAME}
    namespace: blue
    user: ${USER_NAME}
  name: ${USER_NAME}@kind-${KIND_CLUSTER_NAME}
current-context: ${USER_NAME}@kind-${KIND_CLUSTER_NAME}
kind: Config
preferences: {}
users:
- name: ${USER_NAME}
  user:
    client-certificate-data: ${USER_CRT}
    client-key-data: ${USER_KEY}