apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: hosted-cp-cluster3
  namespace: hmc-system
spec:
  template: aws-hosted-cp-0-0-2
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: hmc-system
    region: us-west-1
    workersNumber: 3
    instanceType: t3.large
    vpcID: "vpc-0b25b6bf20bc8c10a"
    subnets:
      - id: "subnet-00e14b3a1145e8b09"
        availabilityZone: "us-west-1b"
    securityGroupIDs:
      - "sg-076933e503e134005"