apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: remote-raspi-single1
spec:
  template: remote-single-standalone-cp-0-1-8
  credential: aws-cluster-identity-cred
  config:
    controlPlane:
      ip: 100.66.0.5

    remoteSSH:
      ip: 100.66.0.5
      port: 22
      user: root
      sshKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACDxSNpgvwIlpy5GU6ytACd1ISPnBjyFvcdWsOjsbbQG3QAAAKCPh0qIj4dK
        iAAAAAtzc2gtZWQyNTUxOQAAACDxSNpgvwIlpy5GU6ytACd1ISPnBjyFvcdWsOjsbbQG3Q
        AAAEDuTcOcZbfLzV+D19ndJDZl+jD2wqxk0U64bwV1Nz0jdvFI2mC/AiWnLkZTrK0AJ3Uh
        I+cGPIW9x1aw6OxttAbdAAAAG21pY2hhZWxATWFjQm9vay1Qcm8tNS5sb2NhbAEC
        -----END OPENSSH PRIVATE KEY-----