---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: k8s-remote-test2
spec:
  clusterName: hosted-cp-cluster3
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: k8s-remote-test2
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: k8s-remote-test2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: k8s-remote-test2
spec:
  version: v1.31.1+k0s.0
  args:
    - --kubelet-extra-args="--node-ip=5.78.109.113"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: k8s-remote-test2
spec:
  address: 5.78.109.113
  port: 22
  user: root
  sshKeyRef:
    # This defines which SSH key to use for connecting to the machine. The Secret needs to have key 'value' with the SSH private key in it.
    name: k8s-remote-test2-ssh-key
---
apiVersion: v1
stringData:
  value: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDxSNpgvwIlpy5GU6ytACd1ISPnBjyFvcdWsOjsbbQG3QAAAKCPh0qIj4dK
    iAAAAAtzc2gtZWQyNTUxOQAAACDxSNpgvwIlpy5GU6ytACd1ISPnBjyFvcdWsOjsbbQG3Q
    AAAEDuTcOcZbfLzV+D19ndJDZl+jD2wqxk0U64bwV1Nz0jdvFI2mC/AiWnLkZTrK0AJ3Uh
    I+cGPIW9x1aw6OxttAbdAAAAG21pY2hhZWxATWFjQm9vay1Qcm8tNS5sb2NhbAEC
    -----END OPENSSH PRIVATE KEY-----
kind: Secret
metadata:
  name: k8s-remote-test2-ssh-key
type: Opaque
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: k8s-remote-test1
spec:
  clusterName: hosted-cp-cluster3
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: k8s-remote-test1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: k8s-remote-test1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: k8s-remote-test1
spec:
  version: v1.31.1+k0s.0
  args:
    - --kubelet-extra-args="--node-ip=5.78.104.77"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: k8s-remote-test1
spec:
  address: 5.78.104.77
  port: 22
  user: root
  sshKeyRef:
    # This defines which SSH key to use for connecting to the machine. The Secret needs to have key 'value' with the SSH private key in it.
    name: k8s-remote-test1-ssh-key
---
apiVersion: v1
stringData:
  value: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDxSNpgvwIlpy5GU6ytACd1ISPnBjyFvcdWsOjsbbQG3QAAAKCPh0qIj4dK
    iAAAAAtzc2gtZWQyNTUxOQAAACDxSNpgvwIlpy5GU6ytACd1ISPnBjyFvcdWsOjsbbQG3Q
    AAAEDuTcOcZbfLzV+D19ndJDZl+jD2wqxk0U64bwV1Nz0jdvFI2mC/AiWnLkZTrK0AJ3Uh
    I+cGPIW9x1aw6OxttAbdAAAAG21pY2hhZWxATWFjQm9vay1Qcm8tNS5sb2NhbAEC
    -----END OPENSSH PRIVATE KEY-----
kind: Secret
metadata:
  name: k8s-remote-test1-ssh-key
type: Opaque