apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: ${NAMESPACE}-aws-${CLUSTERNAME}
  namespace: ${NAMESPACE}
spec:
  template: aws-standalone-cp-0-0-1
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: hmc-system
    region: us-east-2
    publicIP: true
    controlPlaneNumber: 1
    workersNumber: 2
    controlPlane:
      instanceType: t3.small
    worker:
      instanceType: t3.small