---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: azure-cluster-identity
  namespace: hmc-system
spec:
  allowedNamespaces: {}
  clientID: "${AZURE_CLIENT_ID}"
  clientSecret:
    name: azure-cluster-identity-secret
    namespace: hmc-system
  tenantID: "${AZURE_TENANT_ID}"
  type: ServicePrincipal
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-cluster-identity-secret
  namespace: hmc-system
stringData:
  clientSecret: "${AZURE_CLIENT_SECRET}"
type: Opaque
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: azure-cluster-identity-cred
  namespace: hmc-system
spec:
  description: Azure credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: azure-cluster-identity
    namespace: hmc-system
