apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 2a-demos
  namespace: hmc-system
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  insecure: true
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/mirantis/2a-demo/charts