name: Package & Publish Demo Charts

on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: REGISTRY_REPO="oci://ghcr.io/schnitzel/2a-demo/charts" make helm-push

      - name: Prepare manifests
        run: make hmc-dist-release